### ISSUE TITLE
Bad argument #1 (Newest ESX)

### ISSUE THREAD

**Issue by sazo2300** [ESX-Org/esx_weaponshop#48]
When using this resource with no modifications, i get the following error:

```
Error running system event handling function for resource esx_extended: citizen:/scripting/lua/scheduler.lua:24: Failed to execute thread: citizen:/scripting/lua/scheduler.lua:595: bad argument #1 to 'unpack' (table expected, got nil)
stack traceback:
        [C]: in function 'table.unpack'
        citizen:/scripting/lua/scheduler.lua:595: in field '?'
        @esx_extended/server/functions.lua:34: in field 'TriggerServerCallback'
        @esx_extended/server/common.lua:98: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:171: in function <citizen:/scripting/lua/scheduler.lua:170>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:24: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:170: in function <citizen:/scripting/lua/scheduler.lua:134>
```
Might be an error due to a new esx triggerservercallback structure? (new in the fivem scene, so dont know).
I dont have modifications to the two, so i dont really know why its doing this. Specifically i get this error whenever the "buyweapon" registered server callback is called.

Any ideas on what could be wrong?

Thanks in advance

**Comment by boomiiee** [comment]
getting the same issue :/

**Comment by MonsterZockerHD** [comment]
same issue :/

**Comment by p-josue** [comment]
If someone has the same problem I can't tell you a solution but I found the process that trigger this error.
Specially when you restart a resource that use ESX client and server side. I will make an example with 2 differents resources to explain it better

Resource **eventRegister** server.lua
`
ESX.RegisterServerCallback("something", function(source, cb)
    print('Hey!')
    cb()
end)
`
Resource **eventUser** client.lua
`
ESX.TriggerServerCallback('something', function()
    print('Returned!')
end)
`

If you do the following console commands you will get the error
`
start eventRegister
stop eventRegister
start eventUser
`

This is because the ESX object still have the reference to the eventRegister event registered but there is no more this code in the runtime. This mechanism is the same if you have both (server.lua and client.lua) in the same resource and the registration of the event happens a little later than the trigger, example: If in your server.lua you have some code before the registration and in your client you have less code the registration will be take a little more than the trigger and ESX will try to get the old reference to the callback but this reference no exist more because you restarted the resource and will be not refreshed until the server.lua register again the callback.

To avoid this problem try solutions to execute your triggers only after the server registered the callbacks
